In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")
import numpy as dp

from sqlalchemy import create_engine

import random
from faker import Faker
fake = Faker()

# Actor.csv

In [12]:
actores = pd.read_csv("C:/ironhack/w3-project_SQL/data/data_sucio/actor.csv", encoding='latin1') # Cargamos el csv actor

In [4]:
actores.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                  # Tamañano del DF(200 filas/4 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   actor_id     200 non-null    int64 
 1   first_name   200 non-null    object
 2   last_name    200 non-null    object
 3   last_update  200 non-null    object
dtypes: int64(1), object(3)
memory usage: 41.0 KB


In [5]:
actores.head(3)

actor_id first_name last_name          last_update
0         1   PENELOPE   GUINESS  2006-02-15 04:34:33
1         2       NICK  WAHLBERG  2006-02-15 04:34:33
2         3         ED     CHASE  2006-02-15 04:34:33

In [6]:
actores['first_name'] = actores['first_name'].str.capitalize() # Capitalizamos las columnas nombre.
actores['last_name'] = actores['last_name'].str.capitalize() #Capitalizamos las columnas apellido.
actores.head(3)

actor_id first_name last_name          last_update
0         1   Penelope   Guiness  2006-02-15 04:34:33
1         2       Nick  Wahlberg  2006-02-15 04:34:33
2         3         Ed     Chase  2006-02-15 04:34:33

In [7]:
(actores.duplicated(["first_name","last_name"])).unique() # Verificamos que hay duplicados'True'. 

array([False,  True])

In [8]:
(actores.duplicated(["first_name","last_name"])).idxmax() # Verificamos su indice.

109

In [9]:
actores.drop([109], inplace= True) # Eliminamos duplicado segun su indice.

In [10]:
(actores.duplicated(["first_name","last_name"])).unique() # Volvemos a verificar si hay duplicados.

array([False])

In [11]:
actores.iloc[107:111] # Verificamos que tenemos un salto de numeracion debido a la eliminacion del duplicado.

actor_id first_name  last_name          last_update
107       108     Warren      Nolte  2006-02-15 04:34:33
108       109  Sylvester       Dern  2006-02-15 04:34:33
110       111    Cameron  Zellweger  2006-02-15 04:34:33
111       112    Russell     Bacall  2006-02-15 04:34:33

In [12]:
actores = actores.reset_index(drop=True) # Reseteamos el indice.
actores['actor_id'] = range(len(actores)) # Reseteamos la numeracion de 'actor_id'
actores.iloc[107:111] # Verificamos

actor_id first_name  last_name          last_update
107       107     Warren      Nolte  2006-02-15 04:34:33
108       108  Sylvester       Dern  2006-02-15 04:34:33
109       109    Cameron  Zellweger  2006-02-15 04:34:33
110       110    Russell     Bacall  2006-02-15 04:34:33

In [13]:
actores.drop(columns =['last_update'],inplace=True) # eliminamos la columna last_update.

In [14]:
actores['Edad'] = [random.randint(18, 45) for _ in range(len(actores))] # Creamos una columna con edad aleatoria.

In [15]:
# cambiamos el Dtype de cada columna para optimizar la memoria.


for c in actores.select_dtypes(include='object'):
    
    actores[c] = actores[c].astype('category') 
    
    
for c in actores.select_dtypes(include='integer'):
    
    actores[c]=pd.to_numeric(actores[c], downcast='integer')
    
    
actores.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                  # Tamañano del DF(199 filas/4 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   actor_id    199 non-null    int16   
 1   first_name  199 non-null    category
 2   last_name   199 non-null    category
 3   Edad        199 non-null    int8    
dtypes: category(2), int16(1), int8(1)
memory usage: 24.7 KB


# Category.csv

In [13]:
categoria =pd.read_csv("C:/ironhack/w3-project_SQL/data/data_sucio/category.csv",encoding='latin1') # Cargamos el csv category

In [17]:
categoria.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                    # Tamañano del DF(16 filas/3 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   category_id  16 non-null     int64 
 1   name         16 non-null     object
 2   last_update  16 non-null     object
dtypes: int64(1), object(2)
memory usage: 2.4 KB


In [18]:
categoria.head(1)

category_id    name          last_update
0            1  Action  2006-02-15 04:46:27

In [19]:
categoria.drop(columns =['last_update'],inplace=True) # eliminamos la columna last_update.

In [20]:
categoria.head(17)

category_id         name
0             1       Action
1             2    Animation
2             3     Children
3             4     Classics
4             5       Comedy
5             6  Documentary
6             7        Drama
7             8       Family
8             9      Foreign
9            10        Games
10           11       Horror
11           12        Music
12           13          New
13           14       Sci-Fi
14           15       Sports
15           16       Travel

In [21]:
nueva_fila = {'category_id': 17, 'name': 'Unknow'} # agrege una fila nueva por necesidad de cruce con peliculas.
categoria = categoria.append(nueva_fila, ignore_index=True)

In [22]:
categoria.duplicated('name').any() # Verificamos si hay filas duplicadas

False

In [23]:
# cambiamos el Dtype de cada columna para optimizar la memoria.

for c in categoria.select_dtypes(include='object'):
    
    categoria[c] = categoria[c].astype('category') 
    
    
for c in categoria.select_dtypes(include='integer'):
    
    categoria[c]=pd.to_numeric(categoria[c], downcast='integer')

categoria.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                    # Tamañano del DF(16 filas/3 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   category_id  17 non-null     int8    
 1   name         17 non-null     category
dtypes: category(1), int8(1)
memory usage: 1.8 KB


# Film.csv

In [14]:
peli =pd.read_csv("C:/ironhack/w3-project_SQL/data/data_sucio/film.csv",encoding='latin1') # Cargamos el csv film

In [25]:
peli.head(3)

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   

                                         description  release_year  \
0  A Epic Drama of a Feminist And a Mad Scientist...          2006   
1  A Astounding Epistle of a Database Administrat...          2006   
2  A Astounding Reflection of a Lumberjack And a ...          2006   

   language_id  original_language_id  rental_duration  rental_rate  length  \
0            1                   NaN                6         0.99      86   
1            1                   NaN                3         4.99      48   
2            1                   NaN                7         2.99      50   

   replacement_cost rating                  special_features  \
0             20.99     PG  Deleted Scenes,Behind the Scenes   
1             12.99      G           Trailers,Deleted Scenes   
2             18.99  NC-17           Trailers,Deleted Scenes   

           last_update  
0  2006-02-15 05:03:42  
1  2006-02-15 05:03:42  
2  2006-02-15 05:03:42

In [26]:
peli.info() # Verificamos la informacion general del DF(encontramos una columna integra de nulos.)
            # Tamañano del DF(1000 filas/13 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   film_id               1000 non-null   int64  
 1   title                 1000 non-null   object 
 2   description           1000 non-null   object 
 3   release_year          1000 non-null   int64  
 4   language_id           1000 non-null   int64  
 5   original_language_id  0 non-null      float64
 6   rental_duration       1000 non-null   int64  
 7   rental_rate           1000 non-null   float64
 8   length                1000 non-null   int64  
 9   replacement_cost      1000 non-null   float64
 10  rating                1000 non-null   object 
 11  special_features      1000 non-null   object 
 12  last_update           1000 non-null   object 
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB


In [27]:
peli.special_features.unique() #  Aqui tenemos valores unicos de esta columna.
                               # Vamos a dividir las caracteristicas especiales que tiene.

array(['Deleted Scenes,Behind the Scenes', 'Trailers,Deleted Scenes',
       'Commentaries,Behind the Scenes', 'Deleted Scenes', 'Trailers',
       'Commentaries,Deleted Scenes',
       'Trailers,Deleted Scenes,Behind the Scenes',
       'Trailers,Commentaries,Behind the Scenes', 'Trailers,Commentaries',
       'Trailers,Behind the Scenes',
       'Commentaries,Deleted Scenes,Behind the Scenes',
       'Trailers,Commentaries,Deleted Scenes',
       'Trailers,Commentaries,Deleted Scenes,Behind the Scenes',
       'Behind the Scenes', 'Commentaries'], dtype=object)

In [28]:
nuevas_columnas = peli['special_features'].str.get_dummies(',').astype(bool) # Utilizamos Get_Dummies para separar valores unicos donde se enuentre la ",".

In [29]:
peli =pd.concat([peli, nuevas_columnas], axis=1,) # Unimos las nuevas columnas del Get_Dummies al DF original
peli.columns = peli.columns.str.lower().str.replace(' ', '_') # Modificamos el nombre de las columnas para que queden todas iguales.

In [30]:
peli.drop(columns=['original_language_id'], inplace=True) # Eliminamos la columna con valores nulos.
peli.drop(columns=['special_features'], inplace=True) # Eliminamos completamente la columna que aplicamos el Get_Dummies.
peli.drop(columns=['last_update'], inplace=True) # Eliminamos la columna last_update.

In [31]:
peli['title'] = peli['title'].str.capitalize() # Capitalizamos las columnas titulo.

In [32]:
peli.duplicated(['title','description']).unique()   # Verificamos si hay filas duplicadas.

array([False])

In [33]:
# cambiamos el Dtype de cada columna para optimizar la memoria.

for c in peli.select_dtypes(include='object'):
    
    peli[c] = peli[c].astype('category') 
    
    
for c in peli.select_dtypes(include='integer'):
    
    peli[c]=pd.to_numeric(peli[c], downcast='integer')
    
for c in peli.select_dtypes(include='float'):
    
    peli[c]=pd.to_numeric(peli[c], downcast='float')

peli.info(memory_usage='deep') # Volvemos a verificar que no quedan columnas con valores nulos.
                               # Tamañano del DF(1000 filas/15 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   film_id            1000 non-null   int16   
 1   title              1000 non-null   category
 2   description        1000 non-null   category
 3   release_year       1000 non-null   int16   
 4   language_id        1000 non-null   int8    
 5   rental_duration    1000 non-null   int8    
 6   rental_rate        1000 non-null   float32 
 7   length             1000 non-null   int16   
 8   replacement_cost   1000 non-null   float32 
 9   rating             1000 non-null   category
 10  behind_the_scenes  1000 non-null   bool    
 11  commentaries       1000 non-null   bool    
 12  deleted_scenes     1000 non-null   bool    
 13  trailers           1000 non-null   bool    
dtypes: bool(4), category(3), float32(2), int16(3), int8(2)
memory usage: 306.4 KB


In [34]:
peli.head(3)

film_id             title  \
0        1  Academy dinosaur   
1        2    Ace goldfinger   
2        3  Adaptation holes   

                                         description  release_year  \
0  A Epic Drama of a Feminist And a Mad Scientist...          2006   
1  A Astounding Epistle of a Database Administrat...          2006   
2  A Astounding Reflection of a Lumberjack And a ...          2006   

   language_id  rental_duration  rental_rate  length  replacement_cost rating  \
0            1                6         0.99      86             20.99     PG   
1            1                3         4.99      48             12.99      G   
2            1                7         2.99      50             18.99  NC-17   

   behind_the_scenes  commentaries  deleted_scenes  trailers  
0               True         False            True     False  
1              False         False            True      True  
2              False         False            True      True

In [35]:
palabras_clave = ['Action', 'Animation', 'Children', 'Classics', 'Comedy', 'Documentary', 'Drama', 'Family', 'Foreign', 'Games', 'Horror', 'Music', 'New', 'Sci-Fi', 'Sports', 'Travel']

def buscar_palabras_clave(description):
    for i, palabra in enumerate(palabras_clave):
        if palabra.lower() in description.lower():
            return str(i + 1)
    return "17"

peli['category_id'] = peli['description'].apply(buscar_palabras_clave)

peli

film_id              title  \
0          1   Academy dinosaur   
1          2     Ace goldfinger   
2          3   Adaptation holes   
3          4   Affair prejudice   
4          5        African egg   
..       ...                ...   
995      996     Young language   
996      997         Youth kick   
997      998       Zhivago core   
998      999  Zoolander fiction   
999     1000          Zorro ark   

                                           description  release_year  \
0    A Epic Drama of a Feminist And a Mad Scientist...          2006   
1    A Astounding Epistle of a Database Administrat...          2006   
2    A Astounding Reflection of a Lumberjack And a ...          2006   
3    A Fanciful Documentary of a Frisbee And a Lumb...          2006   
4    A Fast-Paced Documentary of a Pastry Chef And ...          2006   
..                                                 ...           ...   
995  A Unbelieveable Yarn of a Boat And a Database ...          2006   
996  A Touching Drama of a Teacher And a Cat who mu...          2006   
997  A Fateful Yarn of a Composer And a Man who mus...          2006   
998  A Fateful Reflection of a Waitress And a Boat ...          2006   
999  A Intrepid Panorama of a Mad Scientist And a B...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                6         0.99      86             20.99   
1              1                3         4.99      48             12.99   
2              1                7         2.99      50             18.99   
3              1                5         2.99     117             26.99   
4              1                6         2.99     130             22.99   
..           ...              ...          ...     ...               ...   
995            1                6         0.99     183              9.99   
996            1                4         0.99     179             14.99   
997            1                6         0.99     105             10.99   
998            1                5         2.99     101             28.99   
999            1                3         4.99      50             18.99   

    rating  behind_the_scenes  commentaries  deleted_scenes  trailers  \
0       PG               True         False            True     False   
1        G              False         False            True      True   
2    NC-17              False         False            True      True   
3        G               True          True           False     False   
4        G              False         False            True     False   
..     ...                ...           ...             ...       ...   
995      G               True         False           False      True   
996  NC-17               True         False           False      True   
997  NC-17              False         False            True     False   
998      R              False         False            True      True   
999  NC-17               True          True           False      True   

    category_id  
0             7  
1            17  
2            17  
3             6  
4             6  
..          ...  
995          17  
996           7  
997          17  
998          17  
999          17  

[1000 rows x 15 columns]

## Inventory.csv

In [15]:
inventario = pd.read_csv('C:/ironhack/w3-project_SQL/data/data_sucio/inventory.csv',encoding='latin1') # Cargamos el csv inventory

In [37]:
inventario.head()

inventory_id  film_id  store_id          last_update
0             1        1         1  2006-02-15 05:09:17
1             2        1         1  2006-02-15 05:09:17
2             3        1         1  2006-02-15 05:09:17
3             4        1         1  2006-02-15 05:09:17
4             5        1         2  2006-02-15 05:09:17

In [38]:
inventario.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                     # Tamañano del DF(1000 filas/4 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   inventory_id  1000 non-null   int64 
 1   film_id       1000 non-null   int64 
 2   store_id      1000 non-null   int64 
 3   last_update   1000 non-null   object
dtypes: int64(3), object(1)
memory usage: 97.8 KB


In [39]:
inventario.duplicated(['inventory_id','film_id','store_id','last_update']).unique() # Verificamos filas duplicadas.

array([False])

In [40]:
# cambiamos el Dtype de cada columna para optimizar la memoria.

for c in inventario.select_dtypes(include='object'):
    
    inventario[c] = inventario[c].astype('category') 
    
    
for c in inventario.select_dtypes(include='integer'):
    
    inventario[c]=pd.to_numeric(inventario[c], downcast='integer')
    

inventario.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                     # Tamañano del DF(1000 filas/4 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   inventory_id  1000 non-null   int16   
 1   film_id       1000 non-null   int16   
 2   store_id      1000 non-null   int8    
 3   last_update   1000 non-null   category
dtypes: category(1), int16(2), int8(1)
memory usage: 6.2 KB


## language.csv

In [16]:
lengua = pd.read_csv('C:/ironhack/w3-project_SQL/data/data_sucio/language.csv', encoding='latin1') # Cargamos el csv language

In [42]:
lengua.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                 # Tamañano del DF(6 filas/3 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   language_id  6 non-null      int64 
 1   name         6 non-null      object
 2   last_update  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 1016.0 bytes


In [43]:
lengua.head(10)

language_id      name          last_update
0            1   English  2006-02-15 05:02:19
1            2   Italian  2006-02-15 05:02:19
2            3  Japanese  2006-02-15 05:02:19
3            4  Mandarin  2006-02-15 05:02:19
4            5    French  2006-02-15 05:02:19
5            6    German  2006-02-15 05:02:19

In [44]:
lengua.drop(columns=['last_update'], inplace=True) # Eliminamos la columna last_update.

In [45]:
lengua.duplicated().any() # verificamos filas duplicadas, no es necesario ya que podemos ver perfectamente los datos que tiene.

False

In [46]:
lengua.head(10)

language_id      name
0            1   English
1            2   Italian
2            3  Japanese
3            4  Mandarin
4            5    French
5            6    German

In [47]:
# cambiamos el Dtype de cada columna para optimizar la memoria.

for c in lengua.select_dtypes(include='object'):
    
    lengua[c] = lengua[c].astype('category') 
    
    
for c in lengua.select_dtypes(include='integer'):
    
    lengua[c]=pd.to_numeric(lengua[c], downcast='integer')
    

lengua.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                 # Tamañano del DF(6 filas/3 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   language_id  6 non-null      int8    
 1   name         6 non-null      category
dtypes: category(1), int8(1)
memory usage: 696.0 bytes


## Old_HDD.csv

In [17]:
old = pd.read_csv('C:/ironhack/w3-project_SQL/data/data_sucio/old_HDD.csv', encoding = 'latin1') # Cargamos el csv old_HDD

In [49]:
old.info(memory_usage='deep') # Verificamos la informacion general del DF.
                              # Tamañano del DF(1000 filas/5 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   first_name    1000 non-null   object
 1   last_name     1000 non-null   object
 2   title         1000 non-null   object
 3   release_year  1000 non-null   int64 
 4   category_id   1000 non-null   int64 
 5   old_id        1000 non-null   int64 
dtypes: int64(3), object(3)
memory usage: 215.4 KB


In [50]:
old.head(3)

first_name last_name                 title  release_year  category_id  \
0   Penelope   Guiness      Academy dinosaur          2006            6   
1   Penelope   Guiness  Anaconda confessions          2006            2   
2   Penelope   Guiness           Angels life          2006           13   

   old_id  
0       0  
1       1  
2       2

In [51]:
old[['first_name', 'last_name', 'title']] = old[['first_name', 'last_name', 'title']].apply(lambda x: x.str.capitalize())
# Capitalizamos las columnas nombre,apellido y titulo.

In [52]:
old.head()

first_name last_name                  title  release_year  category_id  \
0   Penelope   Guiness       Academy dinosaur          2006            6   
1   Penelope   Guiness   Anaconda confessions          2006            2   
2   Penelope   Guiness            Angels life          2006           13   
3   Penelope   Guiness  Bulworth commandments          2006           10   
4   Penelope   Guiness          Cheaper clyde          2006           14   

   old_id  
0       0  
1       1  
2       2  
3       3  
4       4

In [53]:
old['old_id'] = range(len(old))

In [54]:
old.duplicated(['first_name','last_name','title']).unique() # Verificamos filas duplicadas.

array([False])

In [74]:
# cambiamos el Dtype de cada columna para optimizar la memoria.

for c in old.select_dtypes(include='object'):
    
    old[c] = old[c].astype('category') 
    
    
for c in old.select_dtypes(include='integer'):
    
    old[c]=pd.to_numeric(old[c], downcast='integer')
    

old.info(memory_usage='deep')# Verificamos la informacion general del DF.
                             # Tamañano del DF(1000 filas/5 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   first_name    1000 non-null   category
 1   last_name     1000 non-null   category
 2   title         1000 non-null   category
 3   release_year  1000 non-null   int16   
 4   category_id   1000 non-null   int8    
 5   old_id        1000 non-null   int16   
dtypes: category(3), int16(2), int8(1)
memory usage: 74.5 KB


## Rental.csv

In [18]:
rental = pd.read_csv('C:/ironhack/w3-project_SQL/data/data_sucio/rental.csv',encoding='latin1')

In [57]:
rental.head(3)

rental_id          rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30           367          130   
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   

           return_date  staff_id          last_update  
0  2005-05-26 22:04:30         1  2006-02-15 21:30:53  
1  2005-05-28 19:40:33         1  2006-02-15 21:30:53  
2  2005-06-01 22:12:39         1  2006-02-15 21:30:53

In [58]:
(rental.staff_id).unique()

array([1, 2], dtype=int64)

In [59]:
rental.info(memory_usage='deep') # Verificamos la informacion general del DF.
                                 # Tamañano del DF(1000 filas/7 columnas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   rental_id     1000 non-null   int64 
 1   rental_date   1000 non-null   object
 2   inventory_id  1000 non-null   int64 
 3   customer_id   1000 non-null   int64 
 4   return_date   1000 non-null   object
 5   staff_id      1000 non-null   int64 
 6   last_update   1000 non-null   object
dtypes: int64(4), object(3)
memory usage: 254.0 KB


In [60]:
rental.duplicated(['rental_date','inventory_id','customer_id','return_date','staff_id']).unique() 
# verificamos filas duplicadas.

array([False])

In [61]:
# cambiamos el Dtype de cada columna para optimizar la memoria.

for c in rental.select_dtypes(include='object'):
    
    rental[c] = rental[c].astype('category') 
    
    
for c in rental.select_dtypes(include='integer'):
    
    rental[c]=pd.to_numeric(rental[c], downcast='integer')
    

rental.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   rental_id     1000 non-null   int16   
 1   rental_date   1000 non-null   category
 2   inventory_id  1000 non-null   int16   
 3   customer_id   1000 non-null   int16   
 4   return_date   1000 non-null   category
 5   staff_id      1000 non-null   int8    
 6   last_update   1000 non-null   category
dtypes: category(3), int16(3), int8(1)
memory usage: 224.7 KB


# Clientes

In [113]:
# por necesidad del negocio vamos a crear un nuevo archivo con mil clientes imaginarios.

customers = {
    'customer_id': list(range(1000)),  # Corrección aquí
    'nombre': [fake.first_name() for _ in range(1000)],
    'apellido': [fake.last_name() for _ in range(1000)],
    'direccion': [fake.address() for _ in range(1000)],
    'correo_electronico': [fake.email() for _ in range(1000)]}

In [114]:
customer = pd.DataFrame(customers) # lo convertimos en dataframe

In [115]:
customer

customer_id   nombre    apellido  \
0              0     Kari   Velazquez   
1              1  William     Edwards   
2              2  Chelsea      Hanson   
3              3    Amber       Brown   
4              4    Roger    Petersen   
..           ...      ...         ...   
995          995     Carl  Villanueva   
996          996   Edward        Dunn   
997          997    Scott     Salinas   
998          998     Noah       Lopez   
999          999  Charles     Russell   

                                             direccion  \
0                130 Janet Mills\nCarrieview, OH 91585   
1               673 Lewis Valley\nTravisland, UT 82483   
2      4238 Weiss Curve Apt. 427\nCraigville, PR 23062   
3                7802 Amanda Hill\nHollyview, WI 59262   
4       42672 Christopher Via\nSouth Jessica, KY 17093   
..                                                 ...   
995                   Unit 8405 Box 3160\nDPO AP 72827   
996                   Unit 8973 Box 4122\nDPO AE 44848   
997  58348 Black Course Apt. 210\nSouth Andrew, PR ...   
998                   PSC 9675, Box 4576\nAPO AP 27345   
999  6167 Byrd Trafficway Apt. 724\nRobinsonmouth, ...   

               correo_electronico  
0         albertmiles@example.com  
1            colton01@example.org  
2       michaelzavala@example.com  
3         christine25@example.com  
4         daycheyenne@example.com  
..                            ...  
995     collinsjerome@example.net  
996        tracylogan@example.net  
997         probinson@example.com  
998  williamsonashley@example.org  
999           laura48@example.net  

[1000 rows x 5 columns]

In [72]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   nombre              1000 non-null   object
 1   apellido            1000 non-null   object
 2   direccion           1000 non-null   object
 3   correo_electronico  1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB


In [71]:

# Aun que sea creado de una libreria revisamos si hay duplicados.
customer.duplicated(['nombre','apellido','direccion','correo_electronico']).unique() 
                                                                                

array([False])

#  Vamos a crear una plantilla de empleados

In [20]:
# por necesidad del negocio vamos a crear un nuevo archivo con empleados

employee = {
    'staff_id': list(range(1,11)),  # Corrección aquí
    'nombre': [fake.first_name() for _ in range(10)],
    'apellido': [fake.last_name() for _ in range(10)],
    'direccion': [fake.address() for _ in range(10)],
    'correo_electronico': [fake.email() for _ in range(10)]}

In [22]:
employee = pd.DataFrame(employee)

In [23]:
employee

staff_id    nombre    apellido  \
0         1     James       Smith   
1         2  Kimberly     Randall   
2         3  Jennifer      Herman   
3         4     David     Barnett   
4         5   Matthew   Gutierrez   
5         6      Luke      Malone   
6         7     Jamie      Morris   
7         8   Melissa  Mclaughlin   
8         9      Gina       Curry   
9        10    Amanda     Stanley   

                                           direccion  \
0  08203 Robert Rest Apt. 563\nEast Juliemouth, V...   
1  2177 Daniels Mountains Apt. 136\nWest Morganto...   
2           69606 Austin Lane\nLake Donald, AS 40817   
3  5828 Johnson Cliffs Suite 255\nSouth Seanport,...   
4               9522 Evan Port\nRogersside, SD 45683   
5        03832 Cummings Path\nPort William, VT 55175   
6     534 Mary Extension\nNew Abigailmouth, IN 57537   
7             5224 Jill Plain\nFowlerhaven, DE 05265   
8     15092 Keith Ferry\nLake Stephenshire, MT 00993   
9     526 Haynes Wall Apt. 455\nSouth John, OR 82694   

           correo_electronico  
0       cynthia05@example.net  
1     cookcameron@example.net  
2       hwilliams@example.org  
3     austinwendy@example.com  
4         wnguyen@example.net  
5        robert40@example.net  
6  geraldvalencia@example.com  
7         egeorge@example.com  
8         amber98@example.org  
9         yualvin@example.org

In [24]:
employee.to_csv('C:/ironhack/w3-project_SQL/data/data_sucio/staff.csv', index=False)

# Exportación

In [82]:
#exportamos los csv limpios.


categoria.to_csv('data/Data_Clean\category_clean.csv', index=False)
peli.to_csv('data/Data_Clean\film_clean.csv', index=False)
actores.to_csv('data/Data_Clean\actor_clean.csv', index=False)
lengua.to_csv('data/Data_Clean\language_clean.csv', index=False)
rental.to_csv('data/Data_Clean\rental_clean.csv', index=False)
customer.to_csv('data/Data_Clean\customer_clean.csv', index=False)
old.to_csv('data/Data_Clean\old_hdd_clean.csv', index=False)
inventario.to_csv('data/Data_Clean\inventory_clean.csv', index=False)
employee.to_csv('data/Data_Clean\staff_clean.csv', index=False)